[tasks.clippy]
args          = ["clippy", "--workspace", "--all-targets", "--all-features"]
command       = "cargo"
install_crate = "clippy"
workspace     = false

[tasks.generate-schema]
args      = ["run", "--bin", "generate_schema"]
command   = "cargo"
workspace = false

[tasks.audit]
args          = ["audit", "--deny", "warnings"]
command       = "cargo"
install_crate = "cargo-audit"
workspace     = false

[tasks.format]
args          = ["fmt", "--all"]
command       = "cargo"
install_crate = "rustfmt"
workspace     = false

[tasks.fmt]
alias = "format"

[tasks.format-check]
args          = ["fmt", "--all", "--check"]
command       = "cargo"
install_crate = "rustfmt"
workspace     = false

[tasks.docker-up]
script = '''
COMPOSE_FILES="--file docker/docker-compose.yaml"
if [ -f docker/docker-compose.override.yaml ]; then
    COMPOSE_FILES="$COMPOSE_FILES --file docker/docker-compose.override.yaml"
fi
docker compose $COMPOSE_FILES --project-name embers "$@" up --build --force-recreate --detach --wait
'''
workspace = false

[tasks.docker-down]
script = '''
COMPOSE_FILES="--file docker/docker-compose.yaml"
if [ -f docker/docker-compose.override.yaml ]; then
    COMPOSE_FILES="$COMPOSE_FILES --file docker/docker-compose.override.yaml"
fi
docker compose $COMPOSE_FILES --project-name embers "$@" down
'''
workspace = false

[tasks.embers]
script = '''
cd packages/embers
cargo make ${1}
'''
workspace = false
