[tasks.clippy]
args          = ["clippy", "--workspace", "--all-targets", "--all-features"]
command       = "cargo"
install_crate = "clippy"
toolchain     = "nightly"

[tasks.audit]
args          = ["audit"]
command       = "cargo"
install_crate = "cargo-audit"
workspace     = false

[tasks.format]
args          = ["fmt", "--all"]
command       = "cargo"
install_crate = "rustfmt"
toolchain     = "nightly"
workspace     = false

[tasks.fmt]
alias = "format"

[tasks.format-check]
args          = ["fmt", "--all", "--check"]
command       = "cargo"
install_crate = "rustfmt"
toolchain     = "nightly"
workspace     = false

[tasks.docker-up]
args = [
    "compose",
    "--file",
    "docker/docker-compose.yaml",
    "--project-name",
    "embers",
    "up",
    "--build",
    "--force-recreate",
    "--detach",
    "--wait",
]
command = "docker"
workspace = false

[tasks.run]
script = '''
cd packages/${1}
cargo make run
'''
workspace = false
