# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ServiceError.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("ServiceError",)

from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class ServiceError(betterproto2.Message):
    messages: "list[str]" = betterproto2.field(1, betterproto2.TYPE_STRING, repeated=True)


default_message_pool.register_message("servicemodelapi", "ServiceError", ServiceError)
