[package]
name = "etc"
version = "0.1.0"
edition = "2024"

[dependencies]
blake2 = "0.10.6"
bs58 = "0.5.1"
derive_more = { version = "2.0.1", features = ["full"] }
hex = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
