[package]
edition = "2024"
name    = "state-sync"
publish = false
version = "0.1.0"

[dependencies]
anyhow         = { version = "1.0" }
base64         = { version = "0.22" }
clap           = { version = "4.5", features = ["derive"] }
firefly-client = { path = "../firefly-client" }
secp256k1      = { version = "0.31" }
serde          = { version = "1.0", features = ["derive"] }
serde_json     = { version = "1.0" }
tokio          = { version = "1.45", features = ["macros", "rt-multi-thread", "signal"] }
uuid           = { version = "1.17", features = ["serde", "v4"] }

[lints.clippy]
default_trait_access = "allow"
implicit_hasher      = "allow"
match_same_arms      = "allow"
missing_errors_doc   = "allow"
must_use_candidate   = "allow"
too_many_lines       = "allow"

[lints.clippy.pedantic]
level    = "warn"
priority = -1

[lints.clippy.nursery]
level    = "warn"
priority = -1
