[package]
edition = "2024"
name = "server"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { version = "1.0", features = ["std"] }
askama = { version = "0.14" }
blake2 = { version = "0.10" }
bs58 = { version = "0.5" }
chrono = { version = "0.4", features = ["serde"] }
derive_more = { version = "2.0", features = ["full"] }
figment = { version = "0.10", features = ["env"] }
firefly-client = { path = "../firefly-client" }
itertools = { version = "0.14" }
poem = { version = "3.1", features = ["anyhow", "compression", "requestid"] }
poem-openapi = { version = "5.1", features = ["chrono", "swagger-ui"] }
prost = { version = "0.13" }
secp256k1 = { version = "0.31", features = ["serde"] }
serde = { version = "1.0" }
serde_json = { version = "1.0" }
structural-convert = { version = "0.13" }
thiserror = { version = "2.0" }
tokio = { version = "1.45", features = ["macros", "rt-multi-thread", "signal"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.17", features = ["serde", "v7"] }

[lints.clippy]
default_trait_access = "allow"
implicit_hasher = "allow"
missing_errors_doc = "allow"
must_use_candidate = "allow"
too_many_lines = "allow"

[lints.clippy.pedantic]
level = "warn"
priority = -1

[lints.clippy.nursery]
level = "warn"
priority = -1
