[tasks.run]
args                                     = ["run", "--bin", "server"]
command                                  = "cargo"
env.EMBERS__ADDRESS                      = "::1"
env.EMBERS__LOG_LEVEL                    = "info,server=trace"
env.EMBERS__MAINNET__DEPLOY_SERVICE_URL  = "http://localhost:14401"
env.EMBERS__MAINNET__PROPOSE_SERVICE_URL = "http://localhost:14402"
env.EMBERS__MAINNET__READ_NODE_URL       = "http://localhost:14413"
env.EMBERS__MAINNET__SERVICE_KEY         = "232DADA5BBAFC0799D5F370DA04AF70CE438F69F954512B26D6FB5B560B81DFE"
env.EMBERS__MAINNET__WALLETS_ENV_KEY     = "8BDC54B5551812C43428EB172A2079ABBEF13B5370BB7535F78807CDEBA3E7B3"
env.EMBERS__PORT                         = 8080
env.EMBERS__TESTNET__DEPLOY_SERVICE_URL  = "http://localhost:15401"
env.EMBERS__TESTNET__ENV_KEY             = "D1BD29C232D11142E852EEE23482B239AF5494DFA10D64E82A72A8CDF82D5127"
env.EMBERS__TESTNET__PROPOSE_SERVICE_URL = "http://localhost:15402"
env.EMBERS__TESTNET__READ_NODE_URL       = "http://localhost:15413"
env.EMBERS__TESTNET__SERVICE_KEY         = "732240A471E12931D858F147165BA1B52C011B92B9E8CD7959AADF06D7ACE622"
env.RUST_BACKTRACE                       = "full"

[tasks.generate-schema]
args    = ["run", "--bin", "generate_schema"]
command = "cargo"

[tasks.e2e-test]
args    = ["run", "pytest"]
command = "poetry"
