name: Rebuild Dev Container

on:
  push:
    branches: [main]
    paths:
      - ".devcontainer/**"
  pull_request:
    paths:
      - ".devcontainer/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lower case repository name
        env:
          REPOSITORY_NAME: "${{ github.repository }}"
        shell: bash
        run: |
          echo "REPOSITORY_NAME_LC=${REPOSITORY_NAME,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dev container image
        id: build
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ env.REPOSITORY_NAME_LC }}/devcontainer
          runCmd: |
            cargo b -r --bin generate_schema

      - name: Image digest
        run: echo ${{ steps.build.outputs.digest }}
