name: Embers
run-name: Embers ${{ github.event_name == 'push' && 'main' || format('MR {0}', github.event.pull_request.title) }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths-ignore:
      - "docker/**"
      - "docs/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - "docker/**"
      - "docs/**"
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/workflows/actions/setup-rust

      - name: Check formatting
        run: cargo make format-check

      - name: Run security audit
        run: cargo make audit

      - name: Build
        run: cargo make build --all-targets

      - name: Run clippy
        run: cargo make clippy

      - name: Run tests
        run: cargo make test

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        working-directory: ./packages/server/tests
        run: poetry install

      - name: Format tests
        working-directory: ./packages/server/tests
        run: poetry run ruff format --check

      - name: Lint tests
        working-directory: ./packages/server/tests
        run: poetry run ruff check

  generate-schema:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/workflows/actions/setup-rust

      - name: Generate schema
        run: cargo make server generate-schema

      - name: Upload build artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: schema.json
          path: packages/server/schema.json

      - name: Update frontend with new schema.json
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.EMBERS_TOKEN }}
          repository: F1R3FLY-io/embers-frontend
          event-type: update-schema
          client-payload: '{"schema_url": "https://api.github.com/repos/F1R3FLY-io/embers/actions/artifacts/${{ steps.upload-artifact.outputs.artifact-id }}/zip"}'

  publish-docker:
    runs-on: ubuntu-latest

    # if: github.ref == 'refs/heads/main'
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: docker/embers.dockerfile
          context: .
          platforms: linux/amd64, linux/arm64
          push: false
          tags: |
            f1r3flyindustries/embers:latest
            f1r3flyindustries/embers:${{ github.sha }}
