name: Embers
run-name: >-
  Embers ${{
    github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.ref_name ||
    github.event_name == 'push' && github.ref_name == 'main' && 'main' ||
    github.event_name == 'pull_request' && format('MR {0}', github.event.pull_request.title) ||
    github.ref_name
  }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    tags: ["*"]
    paths-ignore:
      - "docker/**"
      - "docs/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - "docker/**"
      - "docs/**"
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/workflows/actions/setup-rust

      - name: Check formatting
        run: cargo make format-check

      - name: Run security audit
        run: cargo make audit

      - name: Build
        run: cargo make check --all-targets

      - name: Run clippy
        run: cargo make clippy

      - name: Run tests
        run: cargo make test

      - name: Start services
        run: cargo make docker-up

      - name: Run embers
        run: cargo make server run &

      - name: Wait for embers
        run: |
          echo "Waiting for 10 seconds for the app to start..."
          sleep 10

      - name: Run embers
        run: cargo make server e2e-test

      - name: Stop services
        if: always()
        run: cargo make docker-down

  lint-python:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/server

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Format tests
        run: poetry run ruff format --check

      - name: Lint tests
        run: poetry run ruff check

  generate-schema:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/workflows/actions/setup-rust

      - name: Generate schema
        run: cargo make server generate-schema

      - name: Upload build artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: schema.json
          path: packages/server/schema.json

      - name: Update frontend with new schema.json
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.EMBERS_TOKEN }}
          repository: F1R3FLY-io/embers-frontend
          event-type: update-schema
          client-payload: '{"schema_url": "https://api.github.com/repos/F1R3FLY-io/embers/actions/artifacts/${{ steps.upload-artifact.outputs.artifact-id }}/zip"}'

  publish-docker:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: f1r3flyindustries/embers
          tags: |
            type=ref, event=tag
            type=raw, value=latest, enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64, linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: docker/embers.dockerfile
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
