name: Embers
run-name: Embers ${{ github.event_name == 'push' && 'main' || format('MR {0}', github.event.pull_request.title) }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths-ignore:
      - "docker/**"
      - "docs/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - "docker/**"
      - "docs/**"
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable, nightly
          components: rustfmt, clippy
          cache: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache cargo tools
        id: cache-cargo-tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/cargo-make
            ~/.cargo/bin/cargo-audit
          key: cargo-tools-${{ runner.os }}

      - name: Install cargo tools
        if: steps.cache-cargo-tools.outputs.cache-hit != 'true'
        run: cargo install cargo-make

      - name: Check formatting
        run: cargo make format-check

      - name: Run security audit
        run: cargo make audit

      - name: Build
        run: cargo build --all-targets

      - name: Run clippy
        run: cargo make clippy

      - name: Run tests
        run: cargo make test
