name: Generate Schema

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lower case repository name
        env:
          REPOSITORY_NAME: "${{ github.repository }}"
        shell: bash
        run: |
          echo "REPOSITORY_NAME_LC=${REPOSITORY_NAME,,}" >> $GITHUB_ENV

      - name: Use Dev Container as runtime
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/${{ env.REPOSITORY_NAME_LC }}/devcontainer
          runCmd: |
            cargo r -r --bin generate_schema

      - name: Upload build artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: schema.json
          path: schema.json

      - uses: echo "${{ steps.upload-artifact.output.artifact-url }}"
